# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import wuxiaworld_v2_pb2 as wuxiaworld__v2__pb2


class NovelsStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNovel = channel.unary_unary(
                '/wuxiaworld.api.v2.Novels/GetNovel',
                request_serializer=wuxiaworld__v2__pb2.GetNovelRequest.SerializeToString,
                response_deserializer=wuxiaworld__v2__pb2.GetNovelResponse.FromString,
                )


class NovelsServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetNovel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NovelsServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNovel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNovel,
                    request_deserializer=wuxiaworld__v2__pb2.GetNovelRequest.FromString,
                    response_serializer=wuxiaworld__v2__pb2.GetNovelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wuxiaworld.api.v2.Novels', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Novels(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetNovel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wuxiaworld.api.v2.Novels/GetNovel',
            wuxiaworld__v2__pb2.GetNovelRequest.SerializeToString,
            wuxiaworld__v2__pb2.GetNovelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class ChaptersStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetChapter = channel.unary_unary(
                '/wuxiaworld.api.v2.Chapters/GetChapter',
                request_serializer=wuxiaworld__v2__pb2.GetChapterRequest.SerializeToString,
                response_deserializer=wuxiaworld__v2__pb2.GetChapterResponse.FromString,
                )
        self.GetChapterList = channel.unary_unary(
                '/wuxiaworld.api.v2.Chapters/GetChapterList',
                request_serializer=wuxiaworld__v2__pb2.GetChapterListRequest.SerializeToString,
                response_deserializer=wuxiaworld__v2__pb2.GetChapterListResponse.FromString,
                )


class ChaptersServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetChapter(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChapterList(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChaptersServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetChapter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChapter,
                    request_deserializer=wuxiaworld__v2__pb2.GetChapterRequest.FromString,
                    response_serializer=wuxiaworld__v2__pb2.GetChapterResponse.SerializeToString,
            ),
            'GetChapterList': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChapterList,
                    request_deserializer=wuxiaworld__v2__pb2.GetChapterListRequest.FromString,
                    response_serializer=wuxiaworld__v2__pb2.GetChapterListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'wuxiaworld.api.v2.Chapters', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Chapters(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetChapter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wuxiaworld.api.v2.Chapters/GetChapter',
            wuxiaworld__v2__pb2.GetChapterRequest.SerializeToString,
            wuxiaworld__v2__pb2.GetChapterResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetChapterList(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/wuxiaworld.api.v2.Chapters/GetChapterList',
            wuxiaworld__v2__pb2.GetChapterListRequest.SerializeToString,
            wuxiaworld__v2__pb2.GetChapterListResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
